/**
 * 
 */
var nations = [{ id:"0",text:"请选择"},
{ id:"1",text:"汉族"},
{ id:"10",text:"朝鲜族"},
{ id:"11",text:"满族"},
{ id:"12",text:"侗族"},
{ id:"13",text:"瑶族"},
{ id:"14",text:"白族"},
{ id:"15",text:"土家族　"},
{ id:"16",text:"哈尼族"},
{ id:"17",text:"哈萨克族"},
{ id:"18",text:"傣族"},
{ id:"19",text:"黎族"},
{ id:"2",text:"蒙古族"},
{ id:"20",text:"傈僳族"},
{ id:"21",text:"佤族"},
{ id:"22",text:"畲族"},
{ id:"23",text:"高山族"},
{ id:"24",text:"拉祜族"},
{ id:"25",text:"水族"},
{ id:"26",text:"东乡族"},
{ id:"27",text:"纳西族"},
{ id:"28",text:"景颇族"},
{ id:"29",text:"柯尔克孜族"},
{ id:"3",text:"回族"},
{ id:"30",text:"土族"},
{ id:"31",text:"达斡尔族"},
{ id:"32",text:"仫佬族"},
{ id:"33",text:"羌族"},
{ id:"34",text:"布朗族"},
{ id:"35",text:"撒拉族"},
{ id:"36",text:"毛南族"},
{ id:"37",text:"仡佬族"},
{ id:"38",text:"锡伯族"},
{ id:"39",text:"阿昌族"},
{ id:"4",text:"藏族"},
{ id:"40",text:"普米族"},
{ id:"41",text:"塔吉克族"},
{ id:"42",text:"怒族"},
{ id:"43",text:"乌孜别克族"},
{ id:"44",text:"俄罗斯族"},
{ id:"45",text:"鄂温克族"},
{ id:"46",text:"德昂族"},
{ id:"47",text:"保安族"},
{ id:"48",text:"裕固族"},
{ id:"49",text:"京族"},
{ id:"5",text:"维吾尔族"},
{ id:"50",text:"塔塔尔族"},
{ id:"51",text:"独龙族"},
{ id:"52",text:"鄂伦春族"},
{ id:"53",text:"赫哲族"},
{ id:"54",text:"门巴族"},
{ id:"55",text:"珞巴族"},
{ id:"56",text:"基诺族"},
{ id:"6",text:"苗族"},
{ id:"7",text:"彝族"},
{ id:"8",text:"壮族"},
{ id:"9",text:"布依族"},
{ id:"97",text:"其他"},
{ id:"98",text:"外国血统中国籍人士"}];


var educations=[{ id:"0",text:"请选择"},
{ id:"11",text:"博士"},
{ id:"12",text:"硕士"},
{ id:"13",text:"本科"},
{ id:"14",text:"大专"},
{ id:"15",text:"中专"},
{ id:"16",text:"高中"},
{ id:"17",text:"初中"}];


var province=[{ id:"0",text:"请选择"},
{ id:"11",text:"北京市"},
{ id:"12",text:"天津市"},
{ id:"13",text:"河北省"},
{ id:"14",text:"山西省"},
{ id:"15",text:"内蒙古"},
{ id:"21",text:"辽宁省"},
{ id:"22",text:"吉林省"},
{ id:"23",text:"黑龙江省"},
{ id:"31",text:"上海市"},
{ id:"32",text:"江苏省"},
{ id:"33",text:"浙江省"},
{ id:"34",text:"安徽省"},
{ id:"35",text:"福建省"},
{ id:"36",text:"江西省"},
{ id:"37",text:"山东省"},
{ id:"41",text:"河南省"},
{ id:"42",text:"湖北省"},
{ id:"43",text:"湖南省"},
{ id:"44",text:"广东省"},
{ id:"45",text:"广西"},
{ id:"46",text:"海南省"},
{ id:"50",text:"重庆市"},
{ id:"51",text:"四川省"},
{ id:"52",text:"贵州省"},
{ id:"53",text:"云南省"},
{ id:"54",text:"西藏"},
{ id:"61",text:"陕西省"},
{ id:"62",text:"甘肃省"},
{ id:"63",text:"青海省"},
{ id:"64",text:"宁夏"},
{ id:"65",text:"新疆"},
{ id:"71",text:"中国台湾"},
{ id:"81",text:"中国香港"},
{ id:"82",text:"中国澳门"},
{ id:"99",text:"国外"}];

var jobtitle = [{id:'0',text:'无'},{id:'1',text:'待聘'},{id:'2',text:'初级'},{id:'3',text:'中级'},{id:'4',text:'副高'},{id:'5',text:'正高'}];

